# Generated by Django 3.2 on 2024-10-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('user_assets', '0002_auto_20241006_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
