# Generated by Django 3.2 on 2024-10-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Other', 'Other')], default='Other', max_length=10)),
            ],
        ),
    ]
