# Generated by Django 3.2 on 2024-10-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
